-- MySQL Script generated by MySQL Workbench
-- 05/03/16 17:00:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema domino
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema domino
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `domino` DEFAULT CHARACTER SET utf8 ;
USE `domino` ;

-- -----------------------------------------------------
-- Table `domino`.`Ranking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domino`.`Ranking` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `num_games` INT NULL,
  `num_victories` INT NULL,
  `num_streaks` INT NULL,
  `best_streak` INT NULL,
  `num_login` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `domino`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domino`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `cpf` INT UNSIGNED NULL,
  `creditos` INT NULL,
  `hash` VARCHAR(16) NULL,
  `perfil` VARCHAR(45) NOT NULL,
  `status` TINYINT(1) NOT NULL,
  `Ranking_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_User_Ranking1_idx` (`Ranking_id` ASC),
  CONSTRAINT `fk_User_Ranking1`
    FOREIGN KEY (`Ranking_id`)
    REFERENCES `domino`.`Ranking` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `domino`.`Session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domino`.`Session` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `User_id` INT NOT NULL,
  `User_id1` INT NOT NULL,
  `aposta` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Session_User1_idx` (`User_id` ASC),
  INDEX `fk_Session_User2_idx` (`User_id1` ASC),
  CONSTRAINT `fk_Session_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `domino`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Session_User2`
    FOREIGN KEY (`User_id1`)
    REFERENCES `domino`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `domino`.`Movements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domino`.`Movements` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `move` VARCHAR(45) NULL,
  `move_timestamp` TIMESTAMP NULL,
  `User_id` INT NOT NULL,
  `Session_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Game_User1_idx` (`User_id` ASC),
  INDEX `fk_Movements_Session1_idx` (`Session_id` ASC),
  CONSTRAINT `fk_Game_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `domino`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movements_Session1`
    FOREIGN KEY (`Session_id`)
    REFERENCES `domino`.`Session` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `domino`.`Campaign`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domino`.`Campaign` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NULL,
  `desconto` FLOAT NULL,
  `vigencia` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `domino`.`Settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domino`.`Settings` (
  `settings` MEDIUMTEXT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `domino`.`Transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domino`.`Transactions` (
  `id` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `valor` FLOAT NULL,
  `quantidade` INT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Transactions_User1_idx` (`User_id` ASC),
  CONSTRAINT `fk_Transactions_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `domino`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `domino`.`Invitations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domino`.`Invitations` (
  `id` INT NOT NULL,
  `email` VARCHAR(512) NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Invitations_User1_idx` (`User_id` ASC),
  CONSTRAINT `fk_Invitations_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `domino`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
